### ISSUE TITLE
Epic: CDE Universe 2023 Website - Limited Version

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/CDE-Universe#1]
## 🚀 Initiate Project

- [x] Create a new repository on GitHub.
- [x] Create a new project using Svelte Create App. [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x] Gitpodify the project. Add to gitpod-io Organization Projects. [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x] Create a new workspace using Gitpod. Share access to respective team members. And read-only access to all Gitpodders.
- [x] Add Branch Protection Rules.

## 🧪 Project Setup

- [x]  Configure Vite [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure Svelte [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure TypeScript [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure ESLint [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure Prettier [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure Husky [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure Netlify-adapter for SvelteKit [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x]  Configure `netlify.toml` [`0653363`](https://github.com/gitpod-io/CDE-Universe/commit/0653363a242c90dcd4a7f5ae5be4481d686978c8)
- [x] #2
- [x] #3

## 🌐 Project Deployment

- [x]  Configure Netlify
- [x]  Create a new site on Netlify.
- [x]  Connect the site to the GitHub repository.
- [x]  Configure the site.
- [x]  Configure Cookieless Analytics using Netlify
- [x]  Deploy the site: https://cde-universe-kumquat.netlify.app/

### 🎨 Initiate the UI Design System
- #5
  - [x] #8
  - [x]  Initiate the UI Layout
  - [x]  Initiate the UI Typography
  - [x]  Initiate the UI Colors
  - [x]  Initiate the UI Icons
  - [x]  Initiate the UI Buttons
  - [x]  Initiate the UI Components
  - [x]  Integrate Required Components

### 🛠️ Building Using Components 
  - [x] Boilerplate Cleanup
  - [x] #10
  - [x] #19
  - [x] #48
  - [x] #11
  - [x] #12
  - [x] #13
  - [x] #49
  - [x] #59

### 💪 Implementation of New Sections
  - [x] #24
  - [x] #21
  - [x] #20
  - [x] #35
  - [x] #38
  - [x] #28

### 🤝 APIs

  - [x] #40 

### ✨ Polish & Cleanup

  - [x] #52
  - [x] #55 
  - [x] #56
  - [x] #62
  - [x] #63
  - [x] #70

## 🎉 Public Release

  - [x]  Configure the site's domain with `cdeuniverse.com` (ping [here in internal conversation](https://gitpod.slack.com/archives/C04UDQ00Q7P/p1679399216650299?thread_ts=1679396146.642239&cid=C04UDQ00Q7P))
  - [x] #7
  - [x] #6
