### ISSUE TITLE
mobile adjustments

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/CDE-Universe#149]
- [ ] the circle is not visible on my phone (safari & Chrome)
![IMG_1318](https://github.com/gitpod-io/CDE-Universe/assets/46345125/d08dbe8e-f881-4584-925d-1167446bbaf1)

- [x] can you reduce the button sizes to fit two next to each other on mobile? - #150
<img width="444" alt="Bildschirmfoto 2023-05-26 um 09 13 16" src="https://github.com/gitpod-io/CDE-Universe/assets/46345125/4796e97e-8fd7-468c-a2be-ffe281e50001">

- [x] can you align the JetBrains logo behind sourcegraph? - #150
<img width="399" alt="Bildschirmfoto 2023-05-26 um 09 15 01" src="https://github.com/gitpod-io/CDE-Universe/assets/46345125/cf259708-8c94-4bd8-920c-9db0f2fdb35c">

- [x] on my phone I can weirdly move all content horizontally. It's not fixed to the center. For gitpod.io it works fine. Could you adjust that for cde universe as well?  - #150

**Comment by Siddhant-K-code** [comment]
That's super weird that ring is not visible on mobile🤯 

![image](https://github.com/gitpod-io/CDE-Universe/assets/55068936/bd9e5c22-390b-45c1-b35b-890dfec90b16)
